server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

<<<<<<< HEAD
  location = /dokumentacio {
    return 301 /dokumentacio/;
  }

  location /dokumentacio/ {
    try_files $uri $uri/ /dokumentacio/index.html;
=======
  location / {
    try_files $uri $uri/ /index.html;
>>>>>>> d3fda18727ce8b2d98d799fc65d84bbb28bad97f
  }

  location /assets/ {
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
<<<<<<< HEAD

  location /dokumentacio/assets/ {
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
=======
>>>>>>> d3fda18727ce8b2d98d799fc65d84bbb28bad97f
}