server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  location = /dokumentacio {
    return 301 /dokumentacio/;
  }

  location /dokumentacio/ {
    try_files $uri $uri/ /dokumentacio/index.html;
  }

  location /assets/ {
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location /dokumentacio/assets/ {
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}